### ISSUE TITLE
Generate rustdoc from README?

### ISSUE THREAD

**Issue by seanpianka** [livioribeiro/cargo-readme#72]
My project uses `#![doc = include_str!("../README.md")]` to generate the rustdoc for the crate from its README. However, I noticed a user forked it just to remove this line, ostensibly since they're using a Rust version < 1.54. 

Does this crate support this opposite direction for the doc generation? Or is there some alternative method for this?

Thanks!

**Comment by danielhenrymantilla** [comment]
@seanpianka I can't speak of this crate, but what you can do is feature-gat that `include_str!` of yours:

```rust
#![cfg_attr(feature = "better-docs",
    doc = include_str!("../README.md"),
)]
```

with some `better-docs = []` feature in your crate which can be enabled by docs.rs:

```toml
[features]
...

better-docs = []  # unstable

[package.metadata.docs.rs]
features = ["better-docs"]
```
